FROM maven:3.9.9-amazoncorretto-21 AS build
COPY . .
RUN mvn clean package -DskipTests
FROM maven:3.9.5-openjdk-21
COPY --from=build /app/target/regret-mail-scheduler-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 587
ENTRYPOINT [ "java" "-jar" "demo.jar" ]


